package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

func main() {
	fmt.Println("hello")

	file, err := os.Open("year-1-bracket-1.json")
	if err != nil {
		log.Fatal(err)
	}

	defer func() {
		err = file.Close()

		if err != nil {
			log.Fatal(err)
		}
	}()

	decoder := json.NewDecoder(file)
	var autoGenerated AutoGenerated
	err = decoder.Decode(&autoGenerated)

	if err != nil {
		log.Fatal(err)
	}

	brackets := autoGenerated.ReduxAsyncConnect.Response.Data.Brackets

	for _, bracket := range brackets {
		if bracket.Dummy {
			continue
		}

		poll := bracket.Poll
		for _, choice := range poll.Choices {
			fmt.Println(choice.Text, choice.Votes)
		}
	}
}
